#!/bin/bash -l
#PBS -N Fgen_ACCESS_Calculation
#PBS -A UWAS0157
#PBS -l walltime=00:20:00
#PBS -q develop@desched1
#PBS -j oe
#PBS -k eod
#PBS -m abe
#PBS -M xingcx2@uw.edu
#PBS -l select=2:ncpus=16:mpiprocs=1:mem=64GB

module load conda/latest
conda activate amoc-env

papermill /glade/u/home/stevenxu/FAIRproject/ARIMA/Model_fitting_test.ipynb /glade/u/home/stevenxu/FAIRproject/ARIMA/Model_fitting_test_result.ipynb
